---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ../../avvo_chef/data_bags
  nodes_path: ../../avvo_chef/nodes
  environments_path: ../../avvo_chef/environments
  roles_path: ../../avvo_chef/roles
  encrypted_data_bag_secret_key_path: ../../avvo_chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[webapp::default]
      - recipe[webapp::database]
    attributes:
    